# Travis CI documentation is here - http://docs.travis-ci.com

git:
  depth: 5

language: node_js

node_js:
  - "8"

before_script:
    - git config --global user.name SundayOyeniyi

notifications:
  email: true

install:
  - yarn install

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"

sudo: false